version: '3.8'

services:
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - prometheus-config:/etc/prometheus
      - /var/run/docker.sock:/var/run/docker.sock # Bind-mount the Docker socket
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    deploy:
      placement:
        constraints: [node.role == manager] # Ensure Prometheus runs only on manager nodes
    labels:
      prometheus: 'true' # Add this label to identify the Prometheus service

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana

volumes:
  prometheus-config:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=10.32.25.118,nolock,rw,soft,nfsvers=4"
      device: ":/mnt/prox-pool/Coolnow/docker/prometheus"

  grafana-data:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=10.32.25.118,nolock,rw,soft,nfsvers=4"
      device: ":/mnt/prox-pool/Coolnow/docker/grafana"
